apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST

  - name: PostgreSQL
    type: postgres
    url: postgres-service:5432
    database: mcp_reliability
    user: mcp_user
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis-service:6379
    jsonData:
      poolSize: 10
      timeout: 10
    secureJsonData:
      password: $REDIS_PASSWORD

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000